version: '2.5.1.7br{build}'


environment:
    matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        GENERATOR: Ninja
        DEPS:
          libsdl2-dev libsdl2-image-dev libsdl2-net-dev libsdl2-mixer-dev libvorbis-dev libpcre2-dev zlib1g-dev libfluidsynth-dev libportmidi-dev libgl-dev
          ninja-build zstd
          
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        GENERATOR: Visual Studio 14 2015 Win64
        DEPS:
          'sdl2:$(PLATFORM)-windows
          sdl2-net:$(PLATFORM)-windows
          sdl2-mixer:$(PLATFORM)-windows
          sdl2-image:$(PLATFORM)-windows
          pcre:$(PLATFORM)-windows
          zlib:$(PLATFORM)-windows
          libvorbis:$(PLATFORM)-windows
          fluidsynth:$(PLATFORM)-windows
          portmidi:$(PLATFORM)-windows
          opengl:$(PLATFORM)-windows'
          
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        GENERATOR: Visual Studio 15 2017 Win64
        DEPS:
          'sdl2:$(PLATFORM)-windows
          sdl2-net:$(PLATFORM)-windows
          sdl2-mixer:$(PLATFORM)-windows
          sdl2-image:$(PLATFORM)-windows
          pcre:$(PLATFORM)-windows
          zlib:$(PLATFORM)-windows
          libvorbis:$(PLATFORM)-windows
          fluidsynth:$(PLATFORM)-windows
          portmidi:$(PLATFORM)-windows
          opengl:$(PLATFORM)-windows'

platform:
  - x64

configuration:
  - Debug
  - Release

before_build:
    # Install libraries
  - cmd: 'vcpkg install %DEPS%'

  - sh:  'sudo apt-get -y update'
  - sh:  'sudo apt-get -y install $DEPS'

    # Setup CMake
  - cmd: 'cmake -G "%GENERATOR%" -S ./prboom2 "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -DDEBUG_LIBNAME_SUFFIX=""'

  - sh:  'export CC=clang CXX=clang++ LD=clang++'                 # compiler choices
  - sh:  'export CFLAGS="-O2" CXXFLAGS="-O2 -stdlib=libstdc++"'   # build options
  - sh:  'cmake -G "$GENERATOR" -S ./prboom2 -DDEBUG_LIBNAME_SUFFIX=""'

after_build:
    # Package PRBoom+ output together into a zip package
  - cmd: '7z a "prboom-plus-win64-${CONFIGURATION}-${APPVEYOR_BUILD_VERSION}.zip" "./*.exe" "./*.wad" "./*.dll"'

  - sh:
      zip -9v "prboom-plus-linux64-${CONFIGURATION}-${APPVEYOR_BUILD_VERSION}.zip"
      "./${CONFIGURATION}/"{prboom-plus{.wad,-game-server},{pr,gl}boom-plus}

build_script:
  - cmd: 'msbuild "PrBoom-Plus.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

  - sh:  'ninja'

build: Script
  #project: $(APPVEYOR_BUILD_FOLDER)/PrBoom-Plus.sln

artifacts:
     - path: prboom-plus-win64-${CONFIGURATION}-${APPVEYOR_BUILD_VERSION}.zip
       name: 'PRBoom+ Windows 64-bit build (MSVC)'
       type: Zip

     - path: prboom-plus-linux64-${CONFIGURATION}-${APPVEYOR_BUILD_VERSION}.zip
       name: 'PRBoom+ Linux 64-bit build (clang)'
       type: Zip

deploy:
  - release: PRBoom+ v$(appveyor_build_version)
    description: '64-bit Windows and Linux builds from AppVeyor.'

    provider: GitHub
    draft: false
    prerelease: false

    artifact: /.*\.(zip|tar.bz2|zst)/

    auth_token:
        secure: 8I+6+9VLJXaYWNCFmUJeF2oZazopqYMJxlmc07fbUXC207BpUdjhBZGI5G0gGWUM

    on:
        branch: appveyor
        APPVEYOR_REPO_TAG: true

branches:
  only:
    - appveyor
