language: c++
dist: bionic

compiler:
    - clang

os:
    - linux

addons:
    apt:
        packages:
         - libsdl2-dev
         - libsdl2-image-dev
         - libsdl2-net-dev
         - libsdl2-mixer-dev
         - libvorbis-dev
         - libpcre2-dev
         - zlib1g-dev
         - libfluidsynth-dev
         - libportmidi-dev
         - libgl-dev
         - ninja-build

before_install:
    - sudo apt-get update

jobs:
    include:
        - name: "Debug build"
          env: "BUILDTYPE=Debug"
        - name: "Release build"
          env: "BUILDTYPE=Release"
    
script:
    - mkdir .build
    - cd .build
    - CC=clang CXX=clang++ LD=clang++ cmake -G Ninja -DCMAKE_BUILD_TYPE=$BUILDTYPE ../prboom2 && ninja

branches:
    only:
    - appveyor