language: c++
dist: bionic

compiler:
    - clang

os:
    - linux

addons:
    apt:
        packages:
         - libsdl2-dev
         - libsdl2-image-dev
         - libsdl2-net-dev
         - libsdl2-mixer-dev
         - libvorbis-dev
         - libpcre2-dev
         - zlib1g-dev
         - libfluidsynth-dev
         - libportmidi-dev
         - libgl-dev
         - ninja-build

before_install:
    - sudo apt-get update

jobs:
    include:
        - name: "Debug build"
          env: "BUILDTYPE=Debug"
        - name: "Release build"
          env: "BUILDTYPE=Release"
    
script:
    - mkdir .build
    - cd .build
    - CC=clang CXX=clang++ LD=clang++ cmake -G Ninja -DCMAKE_BUILD_TYPE=$BUILDTYPE ../prboom2 && ninja

deploy:
    provider: releases
    secure: "e3/XdP/tKtLA1G6b07KsFlPYyvC6If7K4yRecJ8KRShMPXVIvG62TxpmqqOrRlz3QlZH2lwecwnf4t/OAo3jZ9pYK7PqCudOPPWfVvTw/CMdoxSiboC7Pas7MsMR5kp9HtYCL2NWssBPfxID/puMyloa9Irm/77n5mMCO+KYIQOOJGj/3rGlAU02CF07AJ1/FN5Cw1g8wWjNXF2UapyKiPEOav1A7QK2yc8/Kl9tBzjnK++HbicA+Bb7ekOkL2bbYPlyiVIzWJtU17ad9LB3sFqquIVqFSmvNh8F+FZD25RgdUu5pb6c+h+Z9baUVt0dOlboU9Wo65bJO8NEY0j1izVRJOPBKVSqkPJ2h+VdfKorminJ+zR7TxdRPfdQbpxsrYz4q7p7uPKYrVDfGyeJQr6N8VprI9jsTviQYX5hpgGFfqQk4mKAu7fo1kbe057wt4eKOcbS9zezuoAz6L0ygNKv7LWwXhd6am4TGGSrGnsGMiuTCMJiPqu/ObW36m/UF1gIvRvxULLJb/O+SVKSjyjWsLndFsJ5BGqFt4pLXoO6+OO2JxYhcrVQhEuiR/Sj+gabnJxFj8iuGUXlicFtnWccrt1hnotv0Jc0SHAjDy13+8bqOW78YJq6sd9PWn4ylE3NFbFUVf8Jy03WqaJBnev+l/ATAYGH18GCRD8NGdw="
    skip_cleanup: true
    on:
        tags: true
    file:
        - '.build/prboom-plus'
        - '.build/glboom-plus'
        - '.build/prboom-plus-game-server'
        - '.build/prboom-plus.wad'

branches:
    only:
    - appveyor
    