language: c++
dist: bionic

compiler:
    - clang

os:
    - linux

addons:
    apt:
        packages:
         - libsdl2-dev
         - libsdl2-image-dev
         - libsdl2-net-dev
         - libsdl2-mixer-dev
         - libvorbis-dev
         - libpcre2-dev
         - zlib1g-dev
         - libfluidsynth-dev
         - libportmidi-dev
         - libgl-dev

script:
    - cmake 

branches:
    only:
    - appveyor