version: '2.7.1.7br{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug
  - Release

before_build:
    # Install libraries
    - vcpkg install sdl2 sdl2-net sdl2-mixer sdl2-image pcre zlib libvorbis fluidsynth portmidi libmad opengl
        
    # Setup CMake
    - 'cmake -G "Visual Studio 15 2017 Win64" -S ./prboom2 -B ./bin "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"'

after_build:
    # Package PRBoom+ output together
    - '7z a "bin/prboom-plus-$(APPVEYOR_BUILD_VERSION).zip" "bin/$(configuration)/*.exe"'
    - '7z a "bin/prboom-plus-$(APPVEYOR_BUILD_VERSION).zip" "bin/$(configuration)/*.exe"'

artifacts:
    - path: bin/prboom-plus-$(APPVEYOR_BUILD_VERSION).zip
      name: 'PRBoom+'
      type: Zip

build:
  project: $(APPVEYOR_BUILD_FOLDER)/$(APPVEYOR_PROJECT_NAME).sln
