version: '2.7.1.7br{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug
  - Release

before_build:
    # Install libraries
    - 'vcpkg install sdl2:%PLATFORM%-windows'
    - 'vcpkg install sdl2-net:%PLATFORM%-windows'
    - 'vcpkg install sdl2-mixer:%PLATFORM%-windows'
    - 'vcpkg install sdl2-image:%PLATFORM%-windows'
    - 'vcpkg install pcre:%PLATFORM%-windows'
    - 'vcpkg install zlib:%PLATFORM%-windows'
    - 'vcpkg install libvorbis:%PLATFORM%-windows'
    - 'vcpkg install fluidsynth:%PLATFORM%-windows'
    - 'vcpkg install portmidi:%PLATFORM%-windows'
    - 'vcpkg install opengl:%PLATFORM%-windows'
        
    # Setup CMake
    - 'cmake -G "Visual Studio 15 2017 Win64" -S ./prboom2 "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -DDEBUG_LIBNAME_SUFFIX=""'

after_build:
    # Package PRBoom+ output together
    - '7z a "prboom-plus-%APPVEYOR_BUILD_VERSION%.zip" "./%CONFIGURATION%/*.exe"'
    - '7z a "prboom-plus-%APPVEYOR_BUILD_VERSION%.zip" "./%CONFIGURATION%/*.wad"'
    - '7z a "prboom-plus-%APPVEYOR_BUILD_VERSION%.zip" "./%CONFIGURATION%/*.dll"'

artifacts:
    - path: prboom-plus-$(APPVEYOR_BUILD_VERSION).zip
      name: 'PRBoom+'
      type: Zip

build:
  project: $(APPVEYOR_BUILD_FOLDER)/PrBoom-Plus.sln
