version: '2.7.1.7br{build}'

image: Visual Studio 2017

platform:
  - x86
  - x64
 
configuration:
  - Release
  - Debug

before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
